version: "3.8"
name: cinefacil

services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1GB
      restart_policy:
        condition: on-failure
    networks:
      - cf

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1GB
      restart_policy:
        condition: on-failure
    networks:
      - cf

  db:
    build:
      context: ../db
      dockerfile: Dockerfile
    environment:
      POSTGRES_DB: ES2
      POSTGRES_USER: cf
      POSTGRES_PASSWORD: cinefacil
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./logs:/var/log/postgresql
    ports:
      - "5432:5432"
    networks:
      - cf

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@cinefacil.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - cf

networks:
  cf:
    driver: bridge

volumes:
  pgadmin:
  db:
