version: "3.8"
name: cinefacil

services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5084:5084"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1GB
      restart_policy:
        condition: on-failure
    networks:
      rede:
        ipv4_address: 172.16.238.10

  db:
    build:
      context: ../db
      dockerfile: Dockerfile
    environment:
      POSTGRES_DB: ES2
      POSTGRES_USER: cf
      POSTGRES_PASSWORD: cinefacil
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./logs:/var/log/postgresql
    ports:
      - "5432:5432"
    networks:
      rede:
        ipv4_address: 172.16.238.11

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@cinefacil.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - rede

networks:
  rede:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.238.0/24

volumes:
  pgadmin:
  db:
