version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1GB
      restart_policy:
        condition: on-failure
    networks:
      - cf

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1GB
      restart_policy:
        condition: on-failure
    networks:
      - cf

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./logs:/var/log/postgresql
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 2GB
      restart_policy:
        condition: on-failure
    networks:
      - cf

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@cinefacil
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - db
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: 0.5GB
      restart_policy:
        condition: on-failure
    networks:
      - cf

networks:
  cf:
    driver: bridge

volumes:
  pgadmin:
  backend:
  frontend:
  db:
